// Mocks generated by Mockito 5.3.0 from annotations
// in grammar_app/test/data/repositories/quotes_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:grammar_app/data/datasources/quotes_local_datasource.dart'
    as _i3;
import 'package:grammar_app/data/models/quote_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQuoteModel_0 extends _i1.SmartFake implements _i2.QuoteModel {
  _FakeQuoteModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuotesLocalDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuotesLocalDatasourceImpl extends _i1.Mock
    implements _i3.QuotesLocalDatasourceImpl {
  @override
  _i4.Future<_i2.QuoteModel> getRandomQuoteFromRepo() => (super.noSuchMethod(
        Invocation.method(
          #getRandomQuoteFromRepo,
          [],
        ),
        returnValue: _i4.Future<_i2.QuoteModel>.value(_FakeQuoteModel_0(
          this,
          Invocation.method(
            #getRandomQuoteFromRepo,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.QuoteModel>.value(_FakeQuoteModel_0(
          this,
          Invocation.method(
            #getRandomQuoteFromRepo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.QuoteModel>);
}
