// Mocks generated by Mockito 5.3.0 from annotations
// in grammar_app/test/domain/usecases/quotes_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:grammar_app/data/datasources/quotes_local_datasource.dart'
    as _i2;
import 'package:grammar_app/data/repositories/quotes_repo_impl.dart' as _i4;
import 'package:grammar_app/domain/entities/quote_entity.dart' as _i7;
import 'package:grammar_app/domain/failuries/failures.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQuotesLocalDatasource_0 extends _i1.SmartFake
    implements _i2.QuotesLocalDatasource {
  _FakeQuotesLocalDatasource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuotesRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuotesRepoImpl extends _i1.Mock implements _i4.QuotesRepoImpl {
  @override
  _i2.QuotesLocalDatasource get quotesLocalDatasource => (super.noSuchMethod(
        Invocation.getter(#quotesLocalDatasource),
        returnValue: _FakeQuotesLocalDatasource_0(
          this,
          Invocation.getter(#quotesLocalDatasource),
        ),
        returnValueForMissingStub: _FakeQuotesLocalDatasource_0(
          this,
          Invocation.getter(#quotesLocalDatasource),
        ),
      ) as _i2.QuotesLocalDatasource);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.QuoteEntity>>
      getQuoteFromDatasource() => (super.noSuchMethod(
            Invocation.method(
              #getQuoteFromDatasource,
              [],
            ),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.QuoteEntity>>.value(
                    _FakeEither_1<_i6.Failure, _i7.QuoteEntity>(
              this,
              Invocation.method(
                #getQuoteFromDatasource,
                [],
              ),
            )),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<_i6.Failure, _i7.QuoteEntity>>.value(
                    _FakeEither_1<_i6.Failure, _i7.QuoteEntity>(
              this,
              Invocation.method(
                #getQuoteFromDatasource,
                [],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i6.Failure, _i7.QuoteEntity>>);
}
